In [2]:
# CSV = Comma-Separated-Values
# 첫 줄에 column명이 기재되어 있는지 헤더(Header)확인 후 사용
import pandas as pd

In [3]:
burger_df = pd.read_csv("data/burger.csv", index_col="product_name") # 헤더 자동 인식 
# 헤더가 없다면 두번째 파라미터로 header=None
# column명 설정법 파라미터로 names=["product_name","calories","carb","protein","fat","sodium","category"]
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     NaN  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [4]:
# iloc(integer location), loc(컬럼 이름 or 로우 이름 통해)
burger_df.iloc[3, 1]

np.int64(50)

In [5]:
burger_df.iloc[[2, 3], [1, 2]]

                       carb  protein
product_name
Double Whopper           49       48
Double Cheese Whopper    50       52

In [9]:
burger_df.iloc[1:4, :3]

                       calories  carb  protein
product_name
Cheese Whopper              740    50       32
Double Whopper              900    49       48
Double Cheese Whopper       980    50       52

In [10]:
burger_df.loc['Double Whopper', 'protein']

np.int64(48)

In [12]:
burger_df.loc[['Whopper', 'Double Whopper'], 'protein']

product_name
Whopper           28
Double Whopper    48
Name: protein, dtype: int64

In [14]:
burger_df.loc[['Whopper', 'Double Whopper'], ['carb', 'protein', 'fat']]

                carb  protein  fat
product_name
Whopper           49       28   40
Double Whopper    49       48   58

In [15]:
burger_df.loc['Double Whopper':'Bacon King', 'calories':'fat'] # 마지막 값 포함

                       calories  carb  protein  fat
product_name
Double Whopper              900    49       48   58
Double Cheese Whopper       980    50       52   64
Whopper Junior              310    27       13   18
Bacon King                 1150    49       61   79

In [17]:
burger_df['calories']

product_name
Whopper                   660
Cheese Whopper            740
Double Whopper            900
Double Cheese Whopper     980
Whopper Junior            310
Bacon King               1150
Single Stacker King       700
Double Stacker King      1050
Hamburger                 240
Cheeseburger              280
Double Hamburger          350
Double Cheeseburger       390
Crispy Chicken            670
Chicken Nuggets           170
Spicy Chicken Nuggets     210
Name: calories, dtype: int64

In [18]:
burger_df[['calories', 'fat']]

                       calories  fat
product_name
Whopper                     660   40
Cheese Whopper              740   46
Double Whopper              900   58
Double Cheese Whopper       980   64
Whopper Junior              310   18
Bacon King                 1150   79
Single Stacker King         700   42
Double Stacker King        1050   68
Hamburger                   240   10
Cheeseburger                280   13
Double Hamburger            350   18
Double Cheeseburger         390   21
Crispy Chicken              670   41
Chicken Nuggets             170   11
Spicy Chicken Nuggets       210   15

In [20]:
burger_df['Double Whopper': 'Bacon King'] # iloc, loc없이는 row에 대한 슬라이싱만 가능

                       calories  carb  protein  fat  sodium category
product_name
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers

In [21]:
# 특정 조건에 맞는 데이터 필터링
burger_df['calories']

product_name
Whopper                   660
Cheese Whopper            740
Double Whopper            900
Double Cheese Whopper     980
Whopper Junior            310
Bacon King               1150
Single Stacker King       700
Double Stacker King      1050
Hamburger                 240
Cheeseburger              280
Double Hamburger          350
Double Cheeseburger       390
Crispy Chicken            670
Chicken Nuggets           170
Spicy Chicken Nuggets     210
Name: calories, dtype: int64

In [22]:
burger_df['calories'] < 500

product_name
Whopper                  False
Cheese Whopper           False
Double Whopper           False
Double Cheese Whopper    False
Whopper Junior            True
Bacon King               False
Single Stacker King      False
Double Stacker King      False
Hamburger                 True
Cheeseburger              True
Double Hamburger          True
Double Cheeseburger       True
Crispy Chicken           False
Chicken Nuggets           True
Spicy Chicken Nuggets     True
Name: calories, dtype: bool

In [23]:
type(burger_df['calories'] < 500)

pandas.core.series.Series

In [24]:
burger_df.loc[burger_df['calories'] < 500]

                       calories  carb  protein  fat  sodium category
product_name
Whopper Junior              310    27       13   18     0.4  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [25]:
burger_df.loc[burger_df['calories'] < 500, 'protein']

product_name
Whopper Junior           13
Hamburger                13
Cheeseburger             15
Double Hamburger         21
Double Cheeseburger      23
Chicken Nuggets           8
Spicy Chicken Nuggets     8
Name: protein, dtype: int64

In [26]:
burger_df.loc[burger_df['calories'] < 500, ['carb', 'protein']]

                       carb  protein
product_name
Whopper Junior           27       13
Hamburger                26       13
Cheeseburger             27       15
Double Hamburger         26       21
Double Cheeseburger      27       23
Chicken Nuggets          11        8
Spicy Chicken Nuggets    11        8

In [27]:
burger_df.loc[burger_df['calories'] < 500, 'calories':'fat']

                       calories  carb  protein  fat
product_name
Whopper Junior              310    27       13   18
Hamburger                   240    26       13   10
Cheeseburger                280    27       15   13
Double Hamburger            350    26       21   18
Double Cheeseburger         390    27       23   21
Chicken Nuggets             170    11        8   11
Spicy Chicken Nuggets       210    11        8   15

In [28]:
burger_df[burger_df['calories'] < 500]

                       calories  carb  protein  fat  sodium category
product_name
Whopper Junior              310    27       13   18     0.4  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [29]:
mask = burger_df['calories'] < 500
burger_df[mask]

                       calories  carb  protein  fat  sodium category
product_name
Whopper Junior              310    27       13   18     0.4  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [30]:
burger_df.loc[mask, 'calories':'fat']

                       calories  carb  protein  fat
product_name
Whopper Junior              310    27       13   18
Hamburger                   240    26       13   10
Cheeseburger                280    27       15   13
Double Hamburger            350    26       21   18
Double Cheeseburger         390    27       23   21
Chicken Nuggets             170    11        8   11
Spicy Chicken Nuggets       210    11        8   15

In [31]:
# 데이터 값 수정
burger_df.loc['Double Stacker King', 'sodium']

np.float64(nan)

In [32]:
burger_df.loc['Double Stacker King', 'sodium'] = 1.9

In [34]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     1.9  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                280    27       15   13     0.6  Burgers
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [36]:
# row 한 줄
burger_df.loc['Cheeseburger']

calories        280
carb             27
protein          15
fat              13
sodium          0.6
category    Burgers
Name: Cheeseburger, dtype: object

In [39]:
burger_df.loc['Cheeseburger'] = [360, 24, 18, 21, 0.7, 'Burger']

In [40]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.3  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.4  Burgers
Whopper Junior              310    27       13   18     0.4  Burgers
Bacon King                 1150    49       61   79     2.2  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     1.9  Burgers
Hamburger                   240    26       13   10     0.4  Burgers
Cheeseburger                360    24       18   21     0.7   Burger
Double Hamburger            350    26       21   18     0.4  Burgers
Double Cheeseburger         390    27       23   21     0.6  Burgers
Crispy Chicken              670    54       23   41     1.1  Chicken
Chicken Nuggets             170    11        8   11     0.3  Chicken
Spicy Chicken Nuggets       210    11        8   15     0.6  Chicken

In [41]:
# 컬럼 한 줄
burger_df['sodium']

product_name
Whopper                  1.0
Cheese Whopper           1.3
Double Whopper           1.0
Double Cheese Whopper    1.4
Whopper Junior           0.4
Bacon King               2.2
Single Stacker King      1.4
Double Stacker King      1.9
Hamburger                0.4
Cheeseburger             0.7
Double Hamburger         0.4
Double Cheeseburger      0.6
Crispy Chicken           1.1
Chicken Nuggets          0.3
Spicy Chicken Nuggets    0.6
Name: sodium, dtype: float64

In [42]:
burger_df['sodium'] = [1.8, 1.6, 1.3, 1.5, 2.5, 2.6, 1.4, 2.6, 1.6, 1.6, 3.6, 0.7, 3.6, 1.4, 1.3]

In [43]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.8  Burgers
Cheese Whopper              740    50       32   46     1.6  Burgers
Double Whopper              900    49       48   58     1.3  Burgers
Double Cheese Whopper       980    50       52   64     1.5  Burgers
Whopper Junior              310    27       13   18     2.5  Burgers
Bacon King                 1150    49       61   79     2.6  Burgers
Single Stacker King         700    48       35   42     1.4  Burgers
Double Stacker King        1050    49       61   68     2.6  Burgers
Hamburger                   240    26       13   10     1.6  Burgers
Cheeseburger                360    24       18   21     1.6   Burger
Double Hamburger            350    26       21   18     3.6  Burgers
Double Cheeseburger         390    27       23   21     0.7  Burgers
Crispy Chicken              670    54       23   41     3.6  Chicken
Chicken Nuggets             170    11        8   11     1.4  Chicken
Spicy Chicken Nuggets       210    11        8   15     1.3  Chicken

In [44]:
# 컬럼 모든 값 동일
burger_df['sodium'] = 1

In [45]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40       1  Burgers
Cheese Whopper              740    50       32   46       1  Burgers
Double Whopper              900    49       48   58       1  Burgers
Double Cheese Whopper       980    50       52   64       1  Burgers
Whopper Junior              310    27       13   18       1  Burgers
Bacon King                 1150    49       61   79       1  Burgers
Single Stacker King         700    48       35   42       1  Burgers
Double Stacker King        1050    49       61   68       1  Burgers
Hamburger                   240    26       13   10       1  Burgers
Cheeseburger                360    24       18   21       1   Burger
Double Hamburger            350    26       21   18       1  Burgers
Double Cheeseburger         390    27       23   21       1  Burgers
Crispy Chicken              670    54       23   41       1  Chicken
Chicken Nuggets             170    11        8   11       1  Chicken
Spicy Chicken Nuggets       210    11        8   15       1  Chicken

In [47]:
# 새로운 로우 추가
burger_df.loc['Tripple Whopper'] = [1130, 49, 67, 75, 1.1, 'Burger']

In [48]:
burger_df

                       calories  carb  protein  fat  sodium category
product_name
Whopper                     660    49       28   40     1.0  Burgers
Cheese Whopper              740    50       32   46     1.0  Burgers
Double Whopper              900    49       48   58     1.0  Burgers
Double Cheese Whopper       980    50       52   64     1.0  Burgers
Whopper Junior              310    27       13   18     1.0  Burgers
Bacon King                 1150    49       61   79     1.0  Burgers
Single Stacker King         700    48       35   42     1.0  Burgers
Double Stacker King        1050    49       61   68     1.0  Burgers
Hamburger                   240    26       13   10     1.0  Burgers
Cheeseburger                360    24       18   21     1.0   Burger
Double Hamburger            350    26       21   18     1.0  Burgers
Double Cheeseburger         390    27       23   21     1.0  Burgers
Crispy Chicken              670    54       23   41     1.0  Chicken
Chicken Nuggets             170    11        8   11     1.0  Chicken
Spicy Chicken Nuggets       210    11        8   15     1.0  Chicken
Tripple Whopper            1130    49       67   75     1.1   Burger

In [49]:
# 새로운 컬럼 추가
burger_df['brand'] = 'Burger King'
burger_df

,calories,carb,protein,fat,sodium,category,brand
product_name,,,,,,,
Whopper,660,49,28,40,1.0,Burgers,Burger King
Cheese Whopper,740,50,32,46,1.0,Burgers,Burger King
Double Whopper,900,49,48,58,1.0,Burgers,Burger King
Double Cheese Whopper,980,50,52,64,1.0,Burgers,Burger King
Whopper Junior,310,27,13,18,1.0,Burgers,Burger King
Bacon King,1150,49,61,79,1.0,Burgers,Burger King
Single Stacker King,700,48,35,42,1.0,Burgers,Burger King
Double Stacker King,1050,49,61,68,1.0,Burgers,Burger King
Hamburger,240,26,13,10,1.0,Burgers,Burger King
Cheeseburger,360,24,18,21,1.0,Burger,Burger King
Double Hamburger,350,26,21,18,1.0,Burgers,Burger King
Double Cheeseburger,390,27,23,21,1.0,Burgers,Burger King
Crispy Chicken,670,54,23,41,1.0,Chicken,Burger King
Chicken Nuggets,170,11,8,11,1.0,Chicken,Burger King
Spicy Chicken Nuggets,210,11,8,15,1.0,Chicken,Burger King
Tripple Whopper,1130,49,67,75,1.1,Burger,Burger King

In [53]:
# 조건 따라 값 수정
burger_df.loc[burger_df['calories'] >= 500, 'high_calories'] = True
burger_df.loc[burger_df['calories'] < 500, 'high_calories'] = False
burger_df

,calories,carb,protein,fat,sodium,category,brand,high_calories
product_name,,,,,,,,
Whopper,660,49,28,40,1.0,Burgers,Burger King,True
Cheese Whopper,740,50,32,46,1.0,Burgers,Burger King,True
Double Whopper,900,49,48,58,1.0,Burgers,Burger King,True
Double Cheese Whopper,980,50,52,64,1.0,Burgers,Burger King,True
Whopper Junior,310,27,13,18,1.0,Burgers,Burger King,False
Bacon King,1150,49,61,79,1.0,Burgers,Burger King,True
Single Stacker King,700,48,35,42,1.0,Burgers,Burger King,True
Double Stacker King,1050,49,61,68,1.0,Burgers,Burger King,True
Hamburger,240,26,13,10,1.0,Burgers,Burger King,False
Cheeseburger,360,24,18,21,1.0,Burger,Burger King,False
Double Hamburger,350,26,21,18,1.0,Burgers,Burger King,False
Double Cheeseburger,390,27,23,21,1.0,Burgers,Burger King,False
Crispy Chicken,670,54,23,41,1.0,Chicken,Burger King,True
Chicken Nuggets,170,11,8,11,1.0,Chicken,Burger King,False
Spicy Chicken Nuggets,210,11,8,15,1.0,Chicken,Burger King,False
Tripple Whopper,1130,49,67,75,1.1,Burger,Burger King,True